### ISSUE TITLE
Remove RangeAddress from Config

### ISSUE THREAD

**Issue by leandernikolaus** [relab/bandwidth-incentive-simulation#17]
The RangeAddress is duplicate information.
This should be removed from the configuration and instead computed based on the address bits.
Probably the easiest thing is to simply compute it in the getter:
https://github.com/relab/bandwidth-incentive-simulation/blob/72d820360bff351cba876005db3ae23a8d90e5bc/config/get_variables.go#L108

**Comment by VHPL-UIS** [comment]
fixed here 2a193be
