### ISSUE TITLE
Add storage depth to config

### ISSUE THREAD

**Issue by leandernikolaus** [relab/bandwidth-incentive-simulation#22]
Maybe we should put the aimed replication into the config and then calculate the storage depth.
Maybe add calculated parameters to config type.
Maybe move run-related config parameters into separate substruct.

Create a more realistic even option, where you repeatedly pick new addresses at random, until you get one where the neighborhood is not at already above the replication factor.

**Comment by VHPL-UIS** [comment]
I move `Create a more realistic even option, where you repeatedly pick new addresses at random, until you get one where the neighborhood is not at already above the replication factor.` to another issue.

**Comment by leandernikolaus** [comment]
Fixed in #26
